name: Paint Profile (Rolling)

on:
  schedule:
    - cron: "15 8 * * *" # daily, 08:15 UTC (early US morning)
  workflow_dispatch: {}

jobs:
  paint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          persist-credentials: false

      - name: Preflight
        run: |
          test -n "${{ secrets.USER_NAME }}" || (echo "Missing USER_NAME" && exit 1)
          test -n "${{ secrets.USER_EMAIL }}" || (echo "Missing USER_EMAIL" && exit 1)
          test -n "${{ secrets.GH_PAT }}"     || (echo "Missing GH_PAT" && exit 1)

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Generate rolling script (UTC-safe)
        run: |
          node ./remap-rolling.js --align=right ./template.sh > paint.sh
          chmod +x paint.sh
          cp paint.sh /tmp/paint.sh

      - name: Create/overwrite art branch with backdated commits
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          GH_PAT: ${{ secrets.GH_PAT }}
          REPO: ${{ github.repository }}
        run: |
          git config user.name  "$USER_NAME"
          git config user.email "$USER_EMAIL"

          # create orphan worktree for a clean history on 'art-rolling'
          git checkout --orphan art-rolling
          git rm -rf . || true

          # paint into a minimal tree (just foobar.txt)
          bash /tmp/paint.sh

          # push the rewritten art-rolling branch only
          git remote remove origin || true
          git remote add origin https://${GH_PAT}@github.com/${REPO}.git
          git push -f origin art-rolling

          # return to main branch (keeps your files intact there)
          git checkout main
